=== OscarChavarro/vitral/VITRAL/vitral/etc/xml/vsdk.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT Vector3D (#PCDATA)>

<!ELEMENT Point (Vector3D+)>
<!ATTLIST Point type CDATA #REQUIRED>

<!ELEMENT ParametricCubicCurve (Point+)>
<!ATTLIST ParametricCubicCurve approximationSteps CDATA #IMPLIED>

<!ELEMENT ParametricBiCubicPatch (ParametricCubicCurve)>
<!ATTLIST ParametricBiCubicPatch approximationSteps CDATA #IMPLIED>
<!ATTLIST ParametricBiCubicPatch type CDATA #REQUIRED>

=== OscarChavarro/vitral/VITRAL/vitral/testsuite/SceneEditorApplication/patchTest.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ParametricBiCubicPatch SYSTEM "../../etc/xml/vsdk.dtd">
<ParametricBiCubicPatch approximationSteps="12" type="7"><ParametricCubicCurve approximationSteps="50"><Point type="3"><Vector3D>0.0 0.0 0.0</Vector3D><Vector3D>0.5 0.0 0.0</Vector3D><Vector3D>0.0 0.0 0.5</Vector3D></Point><Point type="3"><Vector3D>0.5 0.0 1.0</Vector3D><Vector3D>0.0 0.0 1.0</Vector3D><Vector3D>1.0 0.0 1.0</Vector3D></Point><Point type="3"><Vector3D>0.5 1.0 1.0</Vector3D><Vector3D>1.0 1.0 1.0</Vector3D><Vector3D>0.0 1.0 1.0</Vector3D></Point><Point type="3"><Vector3D>0.0 1.0 0.0</Vector3D><Vector3D>0.0 1.0 0.5</Vector3D><Vector3D>0.5 1.0 0.0</Vector3D></Point><Point type="3"><Vector3D>0.0 0.0 0.0</Vector3D><Vector3D>0.5 0.0 0.0</Vector3D><Vector3D>0.0 0.0 0.5</Vector3D></Point></ParametricCubicCurve></ParametricBiCubicPatch>

=== OscarChavarro/vitral/VITRAL/vitral/testsuite/SceneEditorApplication/curveTest.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ParametricCubicCurve SYSTEM "../../etc/xml/vsdk.dtd">
<ParametricCubicCurve approximationSteps="50"><Point type="3"><Vector3D>0.0 0.0 0.0</Vector3D><Vector3D>0.0 0.0 0.0</Vector3D><Vector3D>0.0 1.0 0.0</Vector3D></Point><Point type="3"><Vector3D>1.0 1.0 0.0</Vector3D><Vector3D>0.0 1.0 0.0</Vector3D><Vector3D>2.0 1.0 0.0</Vector3D></Point><Point type="3"><Vector3D>2.0 0.0 1.0</Vector3D><Vector3D>1.5 -0.5 0.0</Vector3D><Vector3D>0.0 0.0 0.0</Vector3D></Point></ParametricCubicCurve>
